import type { Metadata } from "next";
import { Geologica, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/header";

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin", "cyrillic"], 
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin", "cyrillic"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geologica.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
